name: Environment Variable Demo
on: [push]

env:
  GREETING: "Hi"

jobs:
  printer-greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "${{ env.GREETING }}, World!"